// Bakes the simplified tower models into src/landmark_models.js.
// Run from the repo root:  node tools/bake_landmarks.mjs
// Sources live in tools/landmarks/ (measured from reference models; see its README).
import fs from 'node:fs';
import { TOWERS } from './landmarks/towers.mjs';

const KEEP = ['cn', 'eiffel', 'canton'];
const out = {};
for (const t of TOWERS) {
  if (!KEEP.includes(t.id)) continue;
  const m = t.build();
  out[t.id] = {
    name: t.name, height: t.height, tris: m.tris,
    pos: Array.from(m.pos, (v) => Math.round(v * 100) / 100),
    col: Array.from(m.col),
    idx: Array.from(m.idx),
  };
  console.log(t.id, m.tris, 'triangles');
}
const text = '// Generated by tools/bake_landmarks.mjs. Do not edit by hand.\n' +
  '// Metres, y up, origin at the middle of the base. col is RGB 0-255 per vertex.\n' +
  'export const MODELS = ' + JSON.stringify(out) + ';\n';
fs.writeFileSync(new URL('../src/landmark_models.js', import.meta.url), text);
console.log('wrote src/landmark_models.js', (text.length / 1024).toFixed(0) + ' KB');
